server:
  port: 8282

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
    username: root
    password: test@123

  jpa:
    hibernate:
      ddl-auto: update
